apiVersion: storage.azure.upbound.io/v1beta1
kind: Account
metadata:
  name: corpostracct001
spec:
  forProvider:
    accountKind: StorageV2
    accountReplicationType: LRS
    accountTier: Standard
    isHnsEnabled: true
    location: Canada Central
    resourceGroupName: CrossplaneRG