apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  name: "corpo-vnet-002"
spec:
  forProvider:
    addressSpace:
      - 10.0.0.0/16
    location: Canada Central
    resourceGroupName: CrossplaneRG